SELECT COUNT (*)  FROM APP.LCT_FOTO WHERE 
                                     idtodt =24
                                AND idtlec =3007
                                AND NOMBRE= 'contrato-345710_odt-24_idtlec-3007_fecha-23-07-2018-21:47:49.jpg';
                                
                    
  CREATE TABLE "APP"."LCT_FOTO" 
  
   (	
   "ID" NUMBER,
   "IDTODT" NUMBER  NOT NULL ENABLE, 
	"IDTLEC" NUMBER NOT NULL ENABLE, 
	"CONTRATO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	 CONSTRAINT "LCT_FOTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
  
  
    CREATE SEQUENCE  "APP"."LCT_SQFOTO"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;