  CREATE TABLE "APP"."LCT_ASIGRUTAS" 
   (	"IDTODT" NUMBER(10,0), 
	"IDTLOTFAC" VARCHAR2(6 BYTE), 
	"IDTTRNTYP" VARCHAR2(6 BYTE), 
	"IDTCNTOPR" VARCHAR2(6 BYTE), 
	"FCHASG" DATE DEFAULT sysdate, 
	"FCHUAC" DATE DEFAULT sysdate, 
	"FCHFIN" DATE, 
	"EDOASR" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
  
  -------------------------------------------------------------------------------------------------------------
  
  
  CREATE TABLE "APP"."LCT_DETRTL" 
   (	"IDTRTL" NUMBER(10,0) NOT NULL ENABLE, 
	"ORD" NUMBER(6,0) NOT NULL ENABLE, 
	"EDO" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"FCHCRE" DATE NOT NULL ENABLE, 
	"FCHUAC" DATE NOT NULL ENABLE, 
	"IDTCPR" NUMBER(8,0) NOT NULL ENABLE, 
	"IDTCTR" VARCHAR2(20 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_DETRTL"."IDTRTL" IS 'id de la ruta local';
 
   COMMENT ON COLUMN "APP"."LCT_DETRTL"."ORD" IS 'orden de secuencia';
 
   COMMENT ON COLUMN "APP"."LCT_DETRTL"."EDO" IS 'estado:  NVO';
 
   COMMENT ON COLUMN "APP"."LCT_DETRTL"."FCHCRE" IS 'fecha de creación';
 
   COMMENT ON COLUMN "APP"."LCT_DETRTL"."FCHUAC" IS 'fecha ult cambio';
 
   COMMENT ON COLUMN "APP"."LCT_DETRTL"."IDTCPR" IS 'X7.IDTCPR ID DEL MEDIDOR ';
 
   COMMENT ON COLUMN "APP"."LCT_DETRTL"."IDTCTR" IS 'ID del contrato';
 
   COMMENT ON TABLE "APP"."LCT_DETRTL"  IS 'Rutas locales';
 
 -------------------------------------------------------------------------------------------------------------
 
 
 
  CREATE TABLE "APP"."LCT_EXTRLV" 
   (	"IDTCPR" NUMBER(8,0) NOT NULL ENABLE, 
	"INDANC" NUMBER(10,0) NOT NULL ENABLE, 
	"CNSPRM" NUMBER(12,4) NOT NULL ENABLE, 
	 CONSTRAINT "PKLCT_EXTRLV_IDTCPR" PRIMARY KEY ("IDTCPR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 589824 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_EXTRLV"."IDTCPR" IS 'id del medidor';
 
   COMMENT ON COLUMN "APP"."LCT_EXTRLV"."INDANC" IS 'lectura del mes pasado';
 
   COMMENT ON COLUMN "APP"."LCT_EXTRLV"."CNSPRM" IS 'consumo promedio actual';
 
   COMMENT ON TABLE "APP"."LCT_EXTRLV"  IS 'Tabla temporal que  almacena la finformaciÃ¿Â³n complementaria de lectura X7 en RLV.Se creo este mecanismo porque la consulta de la informaciÃ¿Â³n en X7 directa es lenta y se va a aprovechar el proceso de constiuciÃ¿Â³n de lotes para poblarla.';
 
 -------------------------------------------------------------------------------------------------------------
 
 
  CREATE TABLE "APP"."LCT_FOTO" 
   (	"ID" NUMBER, 
	"IDTODT" NUMBER NOT NULL ENABLE, 
	"IDTLEC" NUMBER NOT NULL ENABLE, 
	"CONTRATO" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	 CONSTRAINT "LCT_FOTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 
 -------------------------------------------------------------------------------------------------------------
 
 
 
  CREATE TABLE "APP"."LCT_LECTURAS" 
   (	"IDTLEC" NUMBER(10,0) NOT NULL ENABLE, 
	"IDTODT" NUMBER(10,0) NOT NULL ENABLE, 
	"IDTPNTLVR" NUMBER(6,0) NOT NULL ENABLE, 
	"IDTPNTCPG" NUMBER(6,0) NOT NULL ENABLE, 
	"IDTCPR" NUMBER(8,0), 
	"RNG1" NUMBER(4,0) NOT NULL ENABLE, 
	"IDTCLT" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"IDTCTR" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"FCHCRE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"FCHUAC" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"FCHLEC" DATE, 
	"FCHVER" DATE, 
	"LECTURA" NUMBER(10,0), 
	"LECTURAVER" NUMBER(10,0), 
	"COORDX" NUMBER(16,6) DEFAULT 0, 
	"COORDY" NUMBER(16,6) DEFAULT 0, 
	"MCOORDX" NUMBER(16,6) DEFAULT 0, 
	"MCOORDY" NUMBER(16,6) DEFAULT 0, 
	"GIRO" VARCHAR2(130 BYTE), 
	"LECTURAPROM" NUMBER(10,0), 
	"LECTURAANT" NUMBER(10,0), 
	"IDTANM1" VARCHAR2(6 BYTE), 
	"IDTANM2" VARCHAR2(6 BYTE), 
	"EDOATL" VARCHAR2(6 BYTE) DEFAULT 'NVO' NOT NULL ENABLE, 
	"BITSCRI" VARCHAR2(500 BYTE) DEFAULT '0' NOT NULL ENABLE, 
	"BITSCRU" VARCHAR2(500 BYTE) DEFAULT '0' NOT NULL ENABLE, 
	"NUMCPR" VARCHAR2(20 BYTE), 
	"DIRECCION" VARCHAR2(2000 BYTE), 
	"IDTACV" VARCHAR2(2 BYTE), 
	"EDOCLIENTE" VARCHAR2(130 BYTE), 
	"LIMINF" NUMBER(10,0), 
	"LIMSUP" NUMBER(10,0), 
	"NOTE" VARCHAR2(254 BYTE), 
	"LIMINF2" NUMBER(10,0), 
	"LIMSUP2" NUMBER(10,0), 
	"NRUEDAS" NUMBER(2,0), 
	"ID_USER" NUMBER, 
	"DATCOU" DATE, 
	"INTENTOS" NUMBER(2,0), 
	"IDEDOCLIENTE" VARCHAR2(6 BYTE), 
	 CONSTRAINT "PKLCT_LECTURAS_IDTLEC" PRIMARY KEY ("IDTLEC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 327680 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."IDTLEC" IS 'id único de lectura';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."IDTODT" IS 'id de la orden de trabajo asociado';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."IDTPNTLVR" IS 'id punto de sumunistro en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."IDTPNTCPG" IS 'id punto de medición en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."IDTCPR" IS 'id del medidor en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."RNG1" IS 'secuencia de la ruta en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."IDTCLT" IS 'id del cliente en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."IDTCTR" IS 'id del contrato en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."FCHCRE" IS 'fecha de asignación del medidor en la ruta asociada';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."FCHUAC" IS 'fecha última actualización';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."FCHLEC" IS 'fecha de la lectura';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."FCHVER" IS 'fecha para la verificación';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."LECTURA" IS 'lectura en atención identificado como IND en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."LECTURAVER" IS 'lectura capturada en el evento de una verificación';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."COORDX" IS 'coordenada x del punto de medición en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."COORDY" IS 'coordenada y del punto de medición en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."MCOORDX" IS 'coordenada x proporcionada por el movil en el levantamiento de lectura';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."MCOORDY" IS 'coordenada y proporcionada por el movil en el levantamiento de lectura';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."GIRO" IS 'giro de negocio';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."LECTURAPROM" IS 'lectura promedio';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."LECTURAANT" IS 'lectura del periodo anterior';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."IDTANM1" IS 'id de anomalía #1';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."IDTANM2" IS 'id de anomalía #2';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."EDOATL" IS 'estado de atención de la lectura  (LCT_VARIABLES.TPOVAR=EDOATL)
NVO -> estado inicial sin captura de lectura
CAP -> Lectura Capturada
SIN -> Sin Captura con motivo
VER -> Solicitud para confirmar la lectyra
CVR ->  Captura Confirmada';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."BITSCRI" IS 'bit de sincronización insert';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."BITSCRU" IS 'bit de sincronización update';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."NUMCPR" IS 'Numero de medidor';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."DIRECCION" IS 'direccion';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."IDTACV" IS 'uso';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."EDOCLIENTE" IS 'estado del cliente';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."LIMINF" IS 'Limite inferior del consumo';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."LIMSUP" IS 'Limite superior del consumo';
 
   COMMENT ON COLUMN "APP"."LCT_LECTURAS"."NOTE" IS 'Comentario del lecturista';
 
   COMMENT ON TABLE "APP"."LCT_LECTURAS"  IS 'Lecturas de los medidos de rutas asignadas';
 

  CREATE OR REPLACE TRIGGER "APP"."TSU_LCT_LECTURAS_LCT_SQLEC" AFTER UPDATE OF idtlec
ON APP.LCT_LECTURAS FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20010,'Cannot update column idtlec in table APP.LCT_LECTURAS as it uses sequence.');
END;

/
ALTER TRIGGER "APP"."TSU_LCT_LECTURAS_LCT_SQLEC" ENABLE;
 

  CREATE OR REPLACE TRIGGER "APP"."TS_LCT_LECTURAS_LCT_SQLEC" BEFORE INSERT
ON APP.LCT_LECTURAS FOR EACH ROW
BEGIN
  :new.idtlec := APP.LCT_SQLEC.nextval;
END;

/
ALTER TRIGGER "APP"."TS_LCT_LECTURAS_LCT_SQLEC" ENABLE;
 
-------------------------------------------------------------------------------------------------------------
 
  CREATE TABLE "APP"."LCT_LIMITES" 
   (	"IDLIMITE" NUMBER, 
	"IDTACV" VARCHAR2(2 BYTE), 
	"CNSINF" NUMBER, 
	"CNSSUP" NUMBER, 
	"LIMINFERIOR1" NUMBER, 
	"LIMINFERIOR2" NUMBER, 
	"LIMSUPERIOR1" NUMBER, 
	"LIMSUPERIOR2" NUMBER, 
	 CONSTRAINT "PK_IDLIMITE" PRIMARY KEY ("IDLIMITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

  CREATE OR REPLACE TRIGGER "APP"."TS_LCT_LIMITES_LCT_SQLIM" BEFORE INSERT
ON APP.LCT_LIMITES FOR EACH ROW
BEGIN
  :new.idlimite := APP.LCT_SQLIM.nextval;
END;
/
ALTER TRIGGER "APP"."TS_LCT_LIMITES_LCT_SQLIM" ENABLE;
 

 -------------------------------------------------------------------------------------------------------------
 
 
  CREATE TABLE "APP"."LCT_LOTES" 
   (	"IDTLOTFAC" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"IDTTRNTYP" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"IDTCNTOPR" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"NBRCPR" NUMBER(6,0) DEFAULT 0 NOT NULL ENABLE, 
	"FCHCRE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"FCHUAC" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"EDOLTE" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"NEWIDTLOFAC" VARCHAR2(6 BYTE), 
	 CONSTRAINT "PKLCT_LOTES_IDTLOTFAC_TRNTYP" PRIMARY KEY ("IDTLOTFAC", "IDTTRNTYP")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_LOTES"."IDTLOTFAC" IS 'id del lote de facturación asociado en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LOTES"."IDTTRNTYP" IS 'identificador de la ruta en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LOTES"."IDTCNTOPR" IS 'id centro operacional en X7';
 
   COMMENT ON COLUMN "APP"."LCT_LOTES"."NBRCPR" IS 'número de medidores de la ruta, en referencia X7.TRNTYPRLV.NBRCPR';
 
   COMMENT ON COLUMN "APP"."LCT_LOTES"."FCHCRE" IS 'fecha de asignación';
 
   COMMENT ON COLUMN "APP"."LCT_LOTES"."FCHUAC" IS 'fecha última actualización';
 
   COMMENT ON COLUMN "APP"."LCT_LOTES"."EDOLTE" IS 'estado de asignación de la ruta (LCT_VARIABLES.TPOVAR=EDOASR)
NVO -> El lote se crea para su asignación
ASG -> Asignado con una OT de referencia
ABN -> Lote Abandonado en X7
FIN -> Lote procesado y facturado';
 
   COMMENT ON TABLE "APP"."LCT_LOTES"  IS 'Lotes que inician en la ejecución de un plan de acción de facturación, su estado representará como es tratado para la gestión de atención a la recolección de sus lecturas.';
 

  -------------------------------------------------------------------------------------------------------------
 
 
 
  CREATE TABLE "APP"."LCT_LOTETIPO" 
   (	"LOTE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"RUTA" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"IDCOPR" NUMBER(10,0) NOT NULL ENABLE, 
	"COPR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"EDO" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_LOTETIPO"."IDCOPR" IS 'ID CENTRO OPERACIONAL';
 
   COMMENT ON COLUMN "APP"."LCT_LOTETIPO"."COPR" IS 'CENTRO OPERACIONAL';
 
   COMMENT ON COLUMN "APP"."LCT_LOTETIPO"."EDO" IS '1 > ACTIVO, 0 > INACTIVO';
 
  -------------------------------------------------------------------------------------------------------------
 


  CREATE TABLE "APP"."LCT_MOBILE" 
   (	"IDTMOB" NUMBER(5,0) NOT NULL ENABLE, 
	"IMEI" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"FCHCRE" DATE NOT NULL ENABLE, 
	"FCHUCX" DATE, 
	"FCHUAC" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"FCHVIG" DATE, 
	"MARCA" VARCHAR2(30 BYTE), 
	"MIODELO" VARCHAR2(30 BYTE), 
	"VERANDROID" VARCHAR2(10 BYTE), 
	"NOTAS" VARCHAR2(2000 BYTE), 
	"EDOOPR" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"COPR" NVARCHAR2(20), 
	 CONSTRAINT "PKLCT_IMEI_IDTIME" PRIMARY KEY ("IDTMOB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_MOBILE"."IDTMOB" IS 'secuencia de imei';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."IMEI" IS 'imei';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."FCHCRE" IS 'fch creación';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."FCHUCX" IS 'fecha última conexión';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."FCHUAC" IS 'fecha última actualización del registro';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."FCHVIG" IS 'fecha de vigencia para la operación';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."MARCA" IS 'marca del teléfono';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."MIODELO" IS 'modelo del teléfono';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."VERANDROID" IS 'versión del s.o. android';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."NOTAS" IS 'notas';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."EDOOPR" IS 'edo del servicio y operación de la unidad
ACT -> activo
INA -> Inactivo
';
 
   COMMENT ON COLUMN "APP"."LCT_MOBILE"."COPR" IS 'centro operacional';
 
   COMMENT ON TABLE "APP"."LCT_MOBILE"  IS 'Catálogo de teléfonos, incluye el IMEI (International Mobile Equiment Identity)';
 

  CREATE OR REPLACE TRIGGER "APP"."TSU_LCT_MOBILE_LCT_SQIME" AFTER UPDATE OF idtmob
ON APP.LCT_MOBILE FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20010,'Cannot update column idtmob in table APP.LCT_MOBILE as it uses sequence.');
END;

/
ALTER TRIGGER "APP"."TSU_LCT_MOBILE_LCT_SQIME" ENABLE;
 

  CREATE OR REPLACE TRIGGER "APP"."TS_LCT_MOBILE_LCT_SQIME" BEFORE INSERT
ON APP.LCT_MOBILE FOR EACH ROW
BEGIN
  :new.idtmob := APP.LCT_SQIME.nextval;
END;

/
ALTER TRIGGER "APP"."TS_LCT_MOBILE_LCT_SQIME" ENABLE;
 
  -------------------------------------------------------------------------------------------------------------
 
  CREATE TABLE "APP"."LCT_ORDENES" 
   (	"IDTODT" NUMBER(10,0) NOT NULL ENABLE, 
	"IDTUSRCRE" NUMBER(10,0) NOT NULL ENABLE, 
	"IDTUSRLCT" NUMBER(10,0) NOT NULL ENABLE, 
	"IDTCNTOPR" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"FCHCRE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"FCHATH" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"FCHUAC" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"FCHFIN" DATE, 
	"IDTLOTFAC" VARCHAR2(6 BYTE), 
	"IDTTRNTYP" VARCHAR2(6 BYTE), 
	"IDTRTALOC" NUMBER(10,0), 
	"EDOODT" VARCHAR2(6 BYTE) DEFAULT NULL, 
	"IDTSCRI" VARCHAR2(500 BYTE), 
	"IDTSCRU" VARCHAR2(500 BYTE), 
	 CONSTRAINT "PKLCT_ODT_IDTODT" PRIMARY KEY ("IDTODT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_ORDENES"."IDTODT" IS 'folio id de la orden de trabajo';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."IDTUSRCRE" IS 'id del usuario que genera la orden de trabajo, vinculado al módulo CNT';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."IDTUSRLCT" IS 'id usuario lecturista que atiende la OT';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."IDTCNTOPR" IS 'id del centro operacional, tomado de la definición de rutas en X7';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."FCHCRE" IS 'fecha de creación de la orden de trabajo';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."FCHATH" IS 'fecha de asigación puede variar si se agenda la atención para una fecha y hora diferente';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."FCHUAC" IS 'fecha última actualización';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."FCHFIN" IS 'fecha finaliza la OT';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."IDTLOTFAC" IS 'id lote de facturación X7.LOTFAC.IDTLOFAC';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."IDTTRNTYP" IS 'id de la ruta en X7.TRNTYP.IDTTRNTYP';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."IDTRTALOC" IS 'id de ruta local';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."EDOODT" IS 'estado de la orden de trabajo (LCT_VARIABLES.TPOVAR=EDOODT)
NVO -> OT Asigmada
EJE -> En ejecución o en propceso
TOT -> Terminada la toma de lecturas (revision)
FIN -> OT finalizada
SUS -> Suependido temporalmente
DES -> OT desestimada.
';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."IDTSCRI" IS 'id de sincronización insert';
 
   COMMENT ON COLUMN "APP"."LCT_ORDENES"."IDTSCRU" IS 'id de sincronización update';
 
   COMMENT ON TABLE "APP"."LCT_ORDENES"  IS 'Ordenes de Trabajo, asignación a lecturistas para la captura de lecturas o de entrega de documentos';
 

  CREATE OR REPLACE TRIGGER "APP"."TRAI_LCT_ORDENES" 
-----------------------------------------------------------------------------------------
--:Pobla la tabla de LCT_LECTURAS
-----------------------------------------------------------------------------------------
AFTER UPDATE ON APP.LCT_ORDENES FOR EACH ROW
 WHEN (
NEW.edoodt = 'NVO'
      ) DECLARE
BEGIN
 LCT_PQLCT.INSERTALECTURA(:NEW.idtodt, :NEW.idtlotfac, NVL(:NEW.idttrntyp,:NEW.idtrtaloc));
END;
/
ALTER TRIGGER "APP"."TRAI_LCT_ORDENES" ENABLE;
 

  CREATE OR REPLACE TRIGGER "APP"."TSU_LCT_ORDENES_LCT_SQODT" AFTER UPDATE OF idtodt
ON APP.LCT_ORDENES FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20010,'Cannot update column idtodt in table APP.LCT_ORDENES as it uses sequence.');
END;

/
ALTER TRIGGER "APP"."TSU_LCT_ORDENES_LCT_SQODT" ENABLE;
 

  CREATE OR REPLACE TRIGGER "APP"."TS_LCT_ORDENES_LCT_SQODT" BEFORE INSERT
ON APP.LCT_ORDENES FOR EACH ROW
BEGIN
  :new.idtodt := APP.LCT_SQODT.nextval;
END;

/
ALTER TRIGGER "APP"."TS_LCT_ORDENES_LCT_SQODT" ENABLE;
 

 
   -------------------------------------------------------------------------------------------------------------
 
  CREATE TABLE "APP"."LCT_PERFIL" 
   (	"IDPERFIL" NUMBER NOT NULL ENABLE, 
	"P_NAME" VARCHAR2(100 BYTE), 
	"STATUS" NUMBER DEFAULT 1 NOT NULL ENABLE, 
	"FECHAIN" DATE, 
	"FECHAFIN" DATE, 
	 CONSTRAINT "LECT_PERFIL_PK" PRIMARY KEY ("IDPERFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_PERFIL"."FECHAIN" IS 'FECHA DE CREACION';
 
   COMMENT ON COLUMN "APP"."LCT_PERFIL"."FECHAFIN" IS 'ULTIMA MODIFICACION';
 

 
 
   -------------------------------------------------------------------------------------------------------------
 
 
  CREATE TABLE "APP"."LCT_RTALOCAL" 
   (	"IDTRTL" NUMBER(10,0) NOT NULL ENABLE, 
	"NOMBRERL" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"EDO" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"FCHCRE" DATE NOT NULL ENABLE, 
	"CNTOPR" VARCHAR2(6 BYTE), 
	 CONSTRAINT "PKLCT_RTL_IDTRTL" PRIMARY KEY ("IDTRTL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_RTALOCAL"."IDTRTL" IS 'id de la lectura';
 
   COMMENT ON COLUMN "APP"."LCT_RTALOCAL"."NOMBRERL" IS 'nombre ruta local';
 
   COMMENT ON COLUMN "APP"."LCT_RTALOCAL"."EDO" IS 'estado:  NVO';
 
   COMMENT ON COLUMN "APP"."LCT_RTALOCAL"."FCHCRE" IS 'estado de la anomalia';
 
   COMMENT ON COLUMN "APP"."LCT_RTALOCAL"."CNTOPR" IS 'centro operacional';
 
   COMMENT ON TABLE "APP"."LCT_RTALOCAL"  IS 'Rutas locales';
 

  CREATE OR REPLACE TRIGGER "APP"."TS_LCT_RTALOCAL_LCT_SQRTL" BEFORE INSERT
ON APP.LCT_RTALOCAL FOR EACH ROW
BEGIN
  :new.idtrtl := APP.LCT_SQRTL.nextval;
END;

/
ALTER TRIGGER "APP"."TS_LCT_RTALOCAL_LCT_SQRTL" ENABLE;
 

  CREATE OR REPLACE TRIGGER "APP"."TSU_LCT_RTALOCAL_LCT_SQRTL" AFTER UPDATE OF idtrtl
ON APP.LCT_RTALOCAL FOR EACH ROW
BEGIN
  RAISE_APPLICATION_ERROR(-20010,'Cannot update column idtrtl in table APP.LCT_RTALOCAL as it uses sequence.');
END;

/
ALTER TRIGGER "APP"."TSU_LCT_RTALOCAL_LCT_SQRTL" ENABLE;
 

  -------------------------------------------------------------------------------------------------------------
 
 
  CREATE TABLE "APP"."LCT_RUTA_TO_USER" 
   (	"ID_RUTA_A_USER" NUMBER NOT NULL ENABLE, 
	"IDTODT" NUMBER NOT NULL ENABLE, 
	"IDUSER" NUMBER NOT NULL ENABLE, 
	"ESTATUS" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "LCT_RUTA_TO_USER_PK" PRIMARY KEY ("ID_RUTA_A_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_RUTA_TO_USER"."IDTODT" IS 'ORDEN DE TRABAJO';
 

  -------------------------------------------------------------------------------------------------------------
 
 
  CREATE TABLE "APP"."LCT_USER" 
   (	"ID_USER" NUMBER NOT NULL ENABLE, 
	"CLAVE" NUMBER NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"AMATERNO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"APATERNO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"EMAIL" VARCHAR2(100 BYTE), 
	"USUARIO" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"PASS" VARCHAR2(1000 BYTE) NOT NULL ENABLE, 
	"GENERO" NUMBER NOT NULL ENABLE, 
	"IDPERFIL" NUMBER NOT NULL ENABLE, 
	"IDTCNTOPR" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"FECHAIN" DATE NOT NULL ENABLE, 
	"FECHAMODIF" DATE NOT NULL ENABLE, 
	"ESTATUS" NUMBER NOT NULL ENABLE, 
	"PHOTO" VARCHAR2(200 BYTE), 
	"LAST_CONEXION" DATE, 
	 CONSTRAINT "LCT_USER_PK" PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_USER"."IDPERFIL" IS 'ID perfil ';
 
   COMMENT ON COLUMN "APP"."LCT_USER"."IDTCNTOPR" IS 'ID CENTRO DE TRABAJO de x7';
 
   COMMENT ON COLUMN "APP"."LCT_USER"."ESTATUS" IS '1 ACTIVO, 0 DESACTIVADO';
 
   COMMENT ON COLUMN "APP"."LCT_USER"."PHOTO" IS 'name';
 

 
  -------------------------------------------------------------------------------------------------------------
 
  CREATE TABLE "APP"."LCT_VARIABLES" 
   (	"IDTVAR" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"TPOVAR" VARCHAR2(6 BYTE) NOT NULL ENABLE, 
	"VALOR" VARCHAR2(1000 BYTE), 
	"DESCRIPCION" VARCHAR2(2000 BYTE), 
	 CONSTRAINT "PKLCT_VARIABLES_IDTVAR" PRIMARY KEY ("IDTVAR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_VARIABLES"."IDTVAR" IS 'id de la variable';
 
   COMMENT ON COLUMN "APP"."LCT_VARIABLES"."TPOVAR" IS 'tipo de variable
';
 
   COMMENT ON COLUMN "APP"."LCT_VARIABLES"."VALOR" IS 'valor';
 
   COMMENT ON COLUMN "APP"."LCT_VARIABLES"."DESCRIPCION" IS 'descripción';
 
   COMMENT ON TABLE "APP"."LCT_VARIABLES"  IS 'variables de contactos';
 

  -------------------------------------------------------------------------------------------------------------
  CREATE SEQUENCE  "APP"."LCT_SQASI"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 46 NOCACHE  ORDER  NOCYCLE ;
  
    CREATE SEQUENCE  "APP"."LCT_SQFOTO"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 127 NOCACHE  ORDER  NOCYCLE ;
  CREATE SEQUENCE  "APP"."LCT_SQIME"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 25 NOCACHE  ORDER  NOCYCLE ;
  
     CREATE SEQUENCE  "APP"."LCT_SQLEC"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 26389 NOCACHE  ORDER  NOCYCLE ;
  
 CREATE SEQUENCE  "APP"."LCT_SQLIM"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 156 NOCACHE  ORDER  NOCYCLE ;
 
    CREATE SEQUENCE  "APP"."LCT_SQMOB"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 6 NOCACHE  ORDER  NOCYCLE ;
    
     CREATE SEQUENCE  "APP"."LCT_SQNOT"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
     
        CREATE SEQUENCE  "APP"."LCT_SQODT"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 71 NOCACHE  ORDER  NOCYCLE ;
        
         CREATE SEQUENCE  "APP"."LCT_SQOLC"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
         
         CREATE SEQUENCE  "APP"."LCT_SQRTL"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 32 NOCACHE  ORDER  NOCYCLE ;
         
          CREATE SEQUENCE  "APP"."LCT_SQRUTATOUSER"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 43 NOCACHE  ORDER  NOCYCLE ;
          
             CREATE SEQUENCE  "APP"."LCT_SQSCR"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  ORDER  NOCYCLE ;
             
               CREATE SEQUENCE  "APP"."LCT_SQUSE"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
 
 
   CREATE SEQUENCE  "APP"."LGN_SQPER"  MINVALUE 1 MAXVALUE 99999999999999 INCREMENT BY 1 START WITH 68 CACHE 20 NOORDER  NOCYCLE ;
 

   CREATE SEQUENCE  "APP"."LGN_SQUSE"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 66 CACHE 20 NOORDER  NOCYCLE ;
 

 
 
  -------------------------------------------------------------------------------------------------------------
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 