--------------------------------------------------------
-- Archivo creado  - viernes-agosto-31-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LCT_USER
--------------------------------------------------------

  CREATE TABLE "APP"."LCT_USER" 
   (	"ID_USER" NUMBER, 
	"CLAVE" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"AMATERNO" VARCHAR2(100 BYTE), 
	"APATERNO" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"USUARIO" VARCHAR2(100 BYTE), 
	"PASS" VARCHAR2(1000 BYTE), 
	"GENERO" NUMBER, 
	"IDPERFIL" NUMBER, 
	"IDTCNTOPR" VARCHAR2(6 BYTE), 
	"FECHAIN" DATE, 
	"FECHAMODIF" DATE, 
	"ESTATUS" NUMBER, 
	"PHOTO" VARCHAR2(200 BYTE), 
	"LAST_CONEXION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
 

   COMMENT ON COLUMN "APP"."LCT_USER"."IDPERFIL" IS 'ID perfil ';
 
   COMMENT ON COLUMN "APP"."LCT_USER"."IDTCNTOPR" IS 'ID CENTRO DE TRABAJO de x7';
 
   COMMENT ON COLUMN "APP"."LCT_USER"."ESTATUS" IS '1 ACTIVO, 0 DESACTIVADO';
 
   COMMENT ON COLUMN "APP"."LCT_USER"."PHOTO" IS 'name';
REM INSERTING into APP.LCT_USER
SET DEFINE OFF;
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (1,2197,'Demo',' ','Demo',null,'demo','demo',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (2,2196,'demo2',' ','demo2',null,'demo2','demo2',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (3,2364,'demo3',' ','Herrera Dzul',null,'demo3','demo3',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (4,2158,'Juana',' ','López Romero',null,'juana','juana',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (5,2433,'Josue',' ','May Pech',null,'JMAY','JMAY2433',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (6,2577,'Alex Adrian',' ','May Tuyub',null,'AMAY','AMAY2577',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (7,2664,'Fernando',' ','Guatemala Cortes',null,'FCORTES','FCORTES2664',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (8,2673,'Miguel Angel',' ','Noh Poot',null,'MNOH','MNOH2673',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (9,2696,'Juan Benjamin',' ','Uicab Yam',null,'JUICAB','JUICAB2696',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (10,200484,'Asuncion',' ','Sanchez Limber',null,'ASANCHEZ','ASANCHEZ200484',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (11,395,'Nelson',' ','Vazquez Mendez',null,'NVAZQUEZ','NVAZQUEZ0395',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (12,2561,'Fernando Miguel',' ','Xool Chi',null,'FXOOL','FXOOL2561',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (13,2746,'Ronaldo',' ','De La Cruz Morales ',null,'RMORALES','RMORALES2746',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (14,2792,'Edgar David',' ','Medina Kau',null,'EMEDINA','EMEDINA2792',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (15,2794,'Miguel Angel',' ','Cortes Vicente',null,'MCORTES','MCORTES2794',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (16,2630,'Miguel Angel',' ','Arroyo Gonzalez',null,'MARROYO','MARROYO2630',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (17,24,'Adolfo Antonio',' ','Uc Garcia',null,'ADUC','ADUCEXT024',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (18,25,'Jairo Yamani',' ','De Dios Cherrez',null,'JCHERREZ','JCHERREZEXT025',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (19,26,'Oscar Adrian',' ','Uc Garcia',null,'OAUC','OAUCEXT026',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (20,2537,'Carlos Asuncion',' ','Cauich Kumul',null,'carlos','carlos',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (21,2506,'Marco Antonio',' ','Cahum Chuc',null,'MCAHUM','MCAHUM2506',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (22,2591,'Yorliany Nicolas',' ','Chan Chan',null,'YNCHAN','YNCHAN2591',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (23,2600,'Jose Manuel',' ','Pool Rivas',null,'JPOOL','JPOOL2600',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (24,2252,'Olga Isabel',' ','Yam Acosta',null,'OYAM','OYAM2252',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (25,2574,'Luis Enrique',' ','Vazquez Gutierrez',null,'ALRODRI','ALRODRI2574',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (26,2623,'Manuel Malaquias',' ','Dzul Canche',null,'MADZUL','MADZUL2623',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (27,200418,'Luis Fernando',' ','Hernandez Gutierrez',null,'LFHERNAN','LFHERNAN200418',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (28,2460,'Manuel Israel',' ','Aviles Montoya',null,'MAVILES','MAVILES2460',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (29,555,'Jesus Del Angel',' ','Velazquez Garcia',null,'JVELAZ','JVELAZ555',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (30,2033,'Hebert Ramon',' ','Caamal Pool',null,'HCAAMAL','HCAAMAL2033',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (31,1893,'Marisol',' ','Cruz Ruiz',null,'MCRUZ','MCRUZ1893',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (32,1882,'Maria De La Luz',' ','Castañeda Dominguez',null,'MCASTANE','MCASTANE1882',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (33,1786,'Andrez',' ','Gomez Canche',null,'AGOMEZ','AGOMEZ1786',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (34,2273,'Giovani',' ','Loria Polanco',null,'GLORIA','GLORIA2273',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (35,2430,'Daniel Emmanuel',' ','España Palma',null,'DPALMA','DPALMA2430',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (36,2820,'Javier',' ','Che Baeza',null,'JCHE','JCHE2820',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (37,2824,'Jose Angel',' ','Pacab Betancourt',null,'JPACAB','JPACAB2824',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (38,2210,'Carlos Angel',' ','De La Cruz Jimenez',null,'CCRUZ','CCRUZ2210',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (39,2290,'Rafael',' ','Sanchez Chi',null,'RSANCHEZ','RSANCHEZ2290',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (40,51,'Roberto',' ','Absalon Betaza',null,'RABSALON','RABSALON0051',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (41,39,'Patricio',' ','Chi Cupul',null,'PCHI','PCHI0039',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (42,41,'Elias',' ','Perez Hernandez',null,'EPEREZH','EPEREZH0041',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (43,43,'Junior Fidel',' ','Reyes Leyva',null,'FIREYES','FIREYES0043',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (44,2278,'Jaime Orlando',' ','Oy Oy',null,'JOY','JOY2278',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (45,2266,'Marco Antonio',' ','Pech Poot',null,'APECH','APECH2266',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (46,2101,'Emilio Cecilio',' ','Gonzalez Magaña',null,'EGONZALE','EGONZALE2101',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (47,59,'Demo playa',' ','Arguello Santana',null,'playa','playa',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (48,3,'Jorge',' ','Gonzalez Martinez',null,'JGONZALEZ','JGONZALEZ0003',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (49,40,'Bartolo',' ','Osorio Rodriguez',null,'BOSORIO','BOSORIO0040',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (50,2478,'Juan Antonio',' ','Tovar Chavez',null,'JTOVAR','JTOVAR2478',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (51,2734,'Luis David',' ','Arellano Dzul',null,'LARELLANO','LARELLANO2734',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (52,1705,'Raul Humberto',' ','Canche Cab',null,'RCANCHE','RCANCHE1705',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (53,1721,'Marcos Elias',' ','May Dzib',null,'MMAY','MMAY1721',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (54,1738,'Jefte',' ','Estrella Chuil',null,'JESTREL','JESTREL1738',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (55,1846,'Anahi De La Concepcion',' ','Roman Aguilar',null,'AROMAN','AROMAN1846',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (56,200468,'Gilberto',' ','Lopez Durante ',null,'GLOPEZ','GLOPEZ200468',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (57,27,'Minerva',' ','Blanco Chacon',null,'MIBLANCO','MIBLANCOEXT027',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (58,28,'Adalberto',' ','Rodriguez Dzul',null,'ARODRIGUEZ','ARODRIGUEZEXT028',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (59,29,'Francisco',' ','Osorio Lopez',null,'FOSORIO','FOSORIOEXT029',3,1,'PDC',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('10/08/18','DD/MM/RR'));
Insert into APP.LCT_USER (ID_USER,CLAVE,NOMBRE,AMATERNO,APATERNO,EMAIL,USUARIO,PASS,GENERO,IDPERFIL,IDTCNTOPR,FECHAIN,FECHAMODIF,ESTATUS,PHOTO,LAST_CONEXION) values (60,2479,'Jimer Eduardo',' ','Garcia Cahum',null,'JEGARCIA','JEGARCIA2479',3,1,'CAN',to_date('27/07/18','DD/MM/RR'),to_date('27/07/18','DD/MM/RR'),1,null,to_date('27/08/18','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index LCT_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "APP"."LCT_USER_PK" ON "APP"."LCT_USER" ("ID_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN" ;
--------------------------------------------------------
--  Constraints for Table LCT_USER
--------------------------------------------------------

  ALTER TABLE "APP"."LCT_USER" ADD CONSTRAINT "LCT_USER_PK" PRIMARY KEY ("ID_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AGUAKAN"  ENABLE;
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("ID_USER" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("CLAVE" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("NOMBRE" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("AMATERNO" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("APATERNO" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("USUARIO" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("PASS" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("GENERO" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("IDPERFIL" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("IDTCNTOPR" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("FECHAIN" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("FECHAMODIF" NOT NULL ENABLE);
 
  ALTER TABLE "APP"."LCT_USER" MODIFY ("ESTATUS" NOT NULL ENABLE);
